name: Build for demo 2

on:
  push:
    branches: [ demo ]

jobs:
  
  deploy:
    
    name: Deploy archive to ubuntu server
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js 19
      uses: actions/setup-node@v1
      with:
        # no support for lts as of now with github actions.
        # issue link : https://github.com/actions/setup-node/issues/26
        # lts/gallium node v19.7.0 (npm v9.5.0)
        node-version: '19.7.0'
        
    - name: Angular CLI install
      run : npm install -g --silent @angular/cli@14.2.12

    - name: Npm install
      run: npm install

    - name: Run tslint
      run : npx tslint src/**/*.ts

    - name: Run build
      run : npm run build:prod

    - name: Copy file using SCP
      run: |
        HOST=${{ secrets.FITER_DEMO_SERVER_URL }}
        USER=${{ secrets.FITER_DEMO_SERVER_USERNAME }}
        SOURCE_FILE='dist/web-app/*'
        DESTINATION_DIR="/home/$USER/mifos/demo2_html/"
        echo "${{ secrets.FITER_DEMO_SERVER_SSH_KEY }}" > key.pem
        chmod 400 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no -l ${{ secrets.FITER_DEMO_SERVER_USERNAME }} ${{ secrets.FITER_DEMO_SERVER_URL }} 'rm -rf /home/$USER/mifos/demo2_html/*'
        scp -i key.pem -o StrictHostKeyChecking=no $SOURCE_FILE $USER@$HOST:$DESTINATION_DIR
        

